services:
  neo4j:
    container_name: neo4j-graph
    image: neo4j:2025.08-community
    ports:
      - "7474:7474"   # HTTP Browser UI
      - "7687:7687"   # Bolt protocol
    volumes:
      - ./neo4j-data/data:/data
      - ./neo4j-data/logs:/logs
      - ./neo4j-data/plugins:/plugins
      - ./neo4j-data/import:/var/lib/neo4j/import
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      # Authentication
      - NEO4J_AUTH=${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-your_secure_password}
  
      # APOC Plugin
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_config_strict__validation_enabled=false
  
      # APOC Configuration
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_trigger_enabled=true
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_apoc_ttl_enabled=true

      # Allow APOC to write to backups folder
      - NEO4J_server_directories_import=/var/lib/neo4j/import,/var/lib/neo4j/backups
  
      # Security
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
  
      # Memory
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=2G
  
      # Transactions
      - NEO4J_db_transaction_timeout=60s
      - NEO4J_db_lock_acquisition_timeout=60s
  
      # Connections
      - NEO4J_server_bolt_thread__pool__min__size=5
      - NEO4J_server_bolt_thread__pool__max__size=400
  
      # Logging
      - NEO4J_server_logs_debug_enabled=false
      - NEO4J_db_logs_query_enabled=INFO
      - NEO4J_db_logs_query_threshold=1s
      
      # Disable telemetry
      - NEO4J_dbms_usage__report_enabled=false

    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: 8G
        reservations:
          cpus: '3'
          memory: 6G
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # File watcher - automatically runs new .cypher files
  neo4j-watcher:
    container_name: neo4j-watcher
    image: python:3.11-slim
    volumes:
      - ./updates:/updates
      - ./watcher.py:/watcher.py
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-your_secure_password}
    command: python -u /watcher.py
    depends_on:
      neo4j:
        condition: service_healthy
    restart: unless-stopped